SELECT * FROM VW_AGENDAMENTO_ATENDIMENTO
FETCH FIRST 5 ROWS ONLY;

SELECT count(*) FROM USUARIOS u

SELECT * FROM ATENDIMENTOS a 

SELECT * FROM PACIENTES p 

SELECT * FROM VW_AGENDAMENTO_AMEI_PORTAL_NEW vaapn 