--QUERY FINAL 
WITH EXAME_FISICO AS (
SELECT '2_ETAPA_OBJETIVA(EXAME FISICO)', ATENDIMENTO_OBJETIVA.ID, ATENDIMENTOS.ID AS ATENDIMENTO_ID2, 
       ATENDIMENTO_OBJETIVA.EXAME_FISICO_CIRURGIA
       FROM   ATENDIMENTO_OBJETIVA
INNER  JOIN ATENDIMENTOS ON ATENDIMENTOS.ID = ATENDIMENTO_OBJETIVA.FK_ATENDIMENTO --AND ATENDIMENTOS.FLG_ATIVO = 1
INNER JOIN AGENDAMENTOS ON ATENDIMENTOS.FK_AGENDAMENTO = AGENDAMENTOS."id"
LEFT   OUTER JOIN MODELO_FORMULARIOS ON MODELO_FORMULARIOS.ID = ATENDIMENTO_OBJETIVA.FK_MODELO_FORMULARIO --AND MODELO_FORMULARIOS.FLG_ATIVO = 1
WHERE  ATENDIMENTO_OBJETIVA.FLG_ATIVO = 1),
HIPOTESES_DIAGNOSTICAS AS (
SELECT '3_ETAPA_AVALICAOA(HIPOTESE_DIAGNOSTICA)', ATEND_AVALIACAO.ID, ATENDIMENTOS.ID AS ATENDIMENTO_ID3,
       ATEND_AVALIACAO.HIPOTESE_DIAGNOSTICA
       FROM   ATEND_AVALIACAO
INNER  JOIN ATENDIMENTOS ON ATENDIMENTOS.ID = ATEND_AVALIACAO.FK_ATENDIMENTO --AND ATENDIMENTOS.FLG_ATIVO = 1
WHERE  ATEND_AVALIACAO.FLG_ATIVO = 1),
EXAMES_SOLICITADOS AS (
SELECT 'EXAMES_SOLICITADOS', ATENDIMENTO_EXAMES.ID AS ID_EXAMES, ATENDIMENTOS.ID AS ATENDIMENTOIDS,
       CASE WHEN ATENDIMENTO_EXAMES.DATA_SOLICITACAO IS NOT NULL THEN TO_CHAR(ATENDIMENTO_EXAMES.DATA_SOLICITACAO,'YYYY/MM/DD')
       ELSE TO_CHAR(ATENDIMENTO_EXAMES.CREATE_AT,'YYYY/MM/DD') END DATA_SOLICITACAO,
       (SELECT LISTAGG(PROCEDIMENTOS."nome",',')
        WITHIN GROUP(ORDER BY PROCEDIMENTOS."nome") 
        FROM   ATEND_EXAME_PROCEDIMENTOS 
        INNER  JOIN PROCEDIMENTOS ON PROCEDIMENTOS."id" = ATEND_EXAME_PROCEDIMENTOS.FK_PROCEDIMENTO
        WHERE  ATEND_EXAME_PROCEDIMENTOS.FK_ATENDIMENTO_EXAME = ATENDIMENTO_EXAMES.ID
        AND    ATEND_EXAME_PROCEDIMENTOS.FLG_ATIVO = 1) PROCEDIMENTO,
       (SELECT LISTAGG(CLASSIFICACAO_MEDICA.CLASSIFICACAO_MEDICA,',')
        WITHIN GROUP(ORDER BY CLASSIFICACAO_MEDICA.CLASSIFICACAO_MEDICA) 
        FROM   ATEND_EXAME_PROBLEMA 
        INNER  JOIN CLASSIFICACAO_MEDICA ON CLASSIFICACAO_MEDICA.ID = ATEND_EXAME_PROBLEMA.FK_CLASSIFICACAO_MEDICA
        WHERE  ATEND_EXAME_PROBLEMA.FK_ATENDIMENTO_EXAME = ATENDIMENTO_EXAMES.ID
        AND    ATEND_EXAME_PROBLEMA.FLG_ATIVO = 1) PROBLEMA
        FROM   ATENDIMENTOS
INNER  JOIN ATENDIMENTO_EXAMES ON FK_ATENDIMENTO = ATENDIMENTOS.ID AND ATENDIMENTO_EXAMES.FLG_ATIVO = 1
INNER  JOIN AGENDAMENTOS ON ATENDIMENTOS.FK_AGENDAMENTO = AGENDAMENTOS."id"
INNER  JOIN ATENDIMENTO_EXAMES ON ATENDIMENTO_EXAMES.FK_ATENDIMENTO = ATENDIMENTOS.ID
LEFT   OUTER JOIN ATENDIMENTO_ARQUIVOS ON ATENDIMENTO_ARQUIVOS.ORIGEM_ID = ATENDIMENTO_EXAMES.ID --AND ATENDIMENTO_ARQUIVOS.ORIGEM = 'RESULTADO_EXAME' AND ATENDIMENTO_ARQUIVOS.FLG_ATIVO = 1
WHERE  ATENDIMENTOS.FLG_ATIVO = 1
),
ANAMNESE AS (
	SELECT '1_ETAPA_SUBJETIVA(ANAMNESE)', RTRIM(UPPER(P."nome")|| ' ' ||UPPER(P."sobrenome")) AS NOME_PACIENTE, S2."sigla" AS SEXO, P."data_nascimento", 
	ATENDIMENTOS.ID AS ID_ATENDIMENTO1, ATENDIMENTOS.FK_AGENDAMENTO  AS AGENDAMENTO_ID, ATENDIMENTOS.ANAMNESE,
       ANAMNESE_MODELOS.NOME ANAMNESE_MODELO, 
       '4_ETAPA_PLANO(CONDUTA)', ATENDIMENTOS.DATA_ATENDIMENTO, I.NOME, I.QTD, I.TIPO_TARJA, I.TIPO_MEDICAMENTO, I.FLG_USO_CONTINUO, I.POSOLOGIA,
       TP.TIPO_PRESCRICAO
       FROM   ATENDIMENTOS
LEFT   OUTER JOIN ANAMNESE_MODELOS ON ANAMNESE_MODELOS.ID = ATENDIMENTOS.FK_ANAMNESE_MODELO AND ANAMNESE_MODELOS.FLG_ATIVO = 1
INNER JOIN AGENDAMENTOS ON ATENDIMENTOS.FK_AGENDAMENTO = AGENDAMENTOS."id"
LEFT JOIN PACIENTES p ON p."id" = agendamentos."paciente_id"
LEFT JOIN AMEI_APP_PROD.SEXO S2 ON S2."id" = P."sexo_id" 
left JOIN ATENDIMENTO_EXAMES ON ATENDIMENTO_EXAMES.FK_ATENDIMENTO  = ATENDIMENTOS.ID
left JOIN ATEND_PRESCRICOES H ON H.FK_ATENDIMENTO = ATENDIMENTOS.ID --AND H.FLG_ATIVO = 1
LEFT JOIN ATEND_PRESC_MEDICAMENTOS I ON I.FK_ATEND_PRESCRICOES = H.ID --AND I.FLG_ATIVO = 1
LEFT JOIN AMEI_APP_PROD.TIPO_PRESCRICAO TP ON TP.ID = H.FK_TIPO_PRESCRICAO
WHERE ATENDIMENTOS.FLG_ATIVO = 1
)
SELECT *
FROM ANAMNESE
LEFT JOIN EXAME_FISICO ON ATENDIMENTO_ID2 = ID_ATENDIMENTO1
LEFT JOIN HIPOTESES_DIAGNOSTICAS ON ATENDIMENTO_ID3 = ID_ATENDIMENTO1
LEFT JOIN EXAMES_SOLICITADOS ON ATENDIMENTOIDS = ID_ATENDIMENTO1
WHERE NOME_PACIENTE NOT IN ('BRUNA DE FREITAS ROSARIO', 'PAULO JONAS RICK', 'RUBEM GUERRA DINIZ', 'FELIPE GOMES BELARMINO') --RETIRANDO USUÁRIOS DE TESTE
--AND NOME_PACIENTE = 'GUILHERME DOS SANTOS SILVA'al
--AND NOME_PACIENTE = 'GUSTAVO JOSELITO GONÇALVES DOS SANTOS'