SELECT * FROM ALL_tables
WHERE OWNER = 'CONSULTA'

--total de registro na tabela de usuários
SELECT count(cu.ID_USUARIO) FROM PORTAL_PACIENTE.CAD_USUARIO cu

--fechar fevereiro
--total de usuários únicos no portal
SELECT count(cu.ID_USUARIO) FROM PORTAL_PACIENTE.CAD_USUARIO cu
WHERE cu.CREATED_AT BETWEEN TO_TIMESTAMP('2023-02-01 00:00:00' , 'yyyy-MM-dd HH24:mi:ss') 
AND TO_TIMESTAMP('2023-02-28 23:59:00', 'yyyy-MM-dd HH24:mi:ss')

--logins totais
SELECT * FROM PORTAL_PACIENTE.CAD_USUARIO_LOG_SESSIONS culs
WHERE culs.DATA_LOG BETWEEN TO_TIMESTAMP('2023-02-01 00:00:00' , 'yyyy-MM-dd HH24:mi:ss') 
AND TO_TIMESTAMP('2023-02-28 00:00:00' , 'yyyy-MM-dd HH24:mi:ss')

--Logins únicos
SELECT COUNT(DISTINCT culs.FK_USUARIO) FROM PORTAL_PACIENTE.CAD_USUARIO_LOG_SESSIONS culs
WHERE culs.DATA_LOG BETWEEN TO_TIMESTAMP('2023-02-01 00:00:00' , 'yyyy-MM-dd HH24:mi:ss') 
AND TO_TIMESTAMP('2023-02-28 00:00:00' , 'yyyy-MM-dd HH24:mi:ss')

--Que acessaram mais de uma vez 
SELECT SUM(COUNT( DISTINCT culs.FK_USUARIO)) AS qtde
FROM PORTAL_PACIENTE.CAD_USUARIO_LOG_SESSIONS culs
WHERE culs.DATA_LOG BETWEEN TO_TIMESTAMP('2023-02-01 00:00:00' , 'yyyy-MM-dd HH24:mi:ss') 
AND TO_TIMESTAMP('2023-02-28 00:00:00' , 'yyyy-MM-dd HH24:mi:ss')
GROUP BY culs.FK_USUARIO
HAVING COUNT(culs.FK_USUARIO) >=2

--novos cadastros feitos no mês de fevereiro
SELECT count( DISTINCT cu.ID_USUARIO) AS Novos 
FROM PORTAL_PACIENTE.CAD_USUARIO cu
WHERE cu.CREATED_AT BETWEEN TO_TIMESTAMP('2023-02-01 00:00:00' , 'yyyy-MM-dd HH24:mi:ss') 
AND TO_TIMESTAMP('2023-02-28 00:00:00' , 'yyyy-MM-dd HH24:mi:ss')

--acesso?
SELECT COUNT(tvu.CPF) FROM PORTAL_PACIENTE.TOKEN_VALIDACAO_USUARIO tvu
WHERE tvu.CPF IS null






